name: Flutter CI/CD

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - 'README.md'
      - 'CLAUDE.md'
      - LICENSE
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - 'README.md'
      - 'CLAUDE.md'
      - LICENSE
  workflow_dispatch:

jobs:
  # Job 1: Verificação de Código e Testes
  verify_code:
    name: Verify Integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        continue-on-error: true

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  # Job 2: Geração da Build (Executado apenas se o Job 1 passar)
  build_apk:
    name: Build APK
    needs: verify_code # <-- Esta linha obriga o GitHub a rodar a verificação primeiro e só avançar se der sucesso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
